user_edit:
    path: /users/{id}/edit
    defaults: { _controller:UserBundle:User:edit }
    requirements:
        id: '\d+'
    
user_list:
    path: /users
    defaults: { _controller:UserBundle:User:list }
    
user_new:
    path: /users/new
    defaults: { _controller:UserBundle:User:new }

user_display:
    path: /users/{id}
    defaults: { _controller:UserBundle:User:display }
    requirements:
        id: '\d+'