user_edit:
    path: /users/edit/{id}
    defaults: { _controller:UserBundle:User:edit, id :1 }
    requirements:
        id: '\d+'
    
user_list:
    path: /users
    defaults: { _controller:UserBundle:User:list, page :1 }
    requirements:
        page: \d+
     
user_new:
    path: /users/new
    defaults: { _controller:UserBundle:User:new }

user_display:
    path: /users/{id}
    defaults: { _controller:UserBundle:User:display }
    requirements:
        id: '\d+'
        
admin:
    path: /admin
    defaults: { _controller:UserBundle:Admin:manage }
    
admin_remove:
    path: /admin/remove/{tableName}/{id}
    defaults: { _controller:UserBundle:Admin:remove }
    requirements:
        id: '\d+'